In [1]:
import pandas as pd
import numpy as np

In [2]:
test= pd.read_csv('E:/University of Bremen MSc/masters_thesis/IAT_sebastian/dataset_15_april_10000_1.csv')

In [3]:
test.info()
test.head()
# df = pd.read_csv("E:/University of Bremen MSc/masters_thesis/IAT_sebastian/dataset_15_april_10000_1.csv", usecols = ['longTime'])
# print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 4220 entries, row ID to RWWIHOSUMAV0
dtypes: float64(4218), int64(1), object(1)
memory usage: 322.0+ MB


row ID       longTime  AEAGHOAWE2T1  AEAGHOAWE2A0  AEAGHOAWE2T0  \
0   Row0  1555311120000     74.451979     19.111606     98.371549   
1   Row1  1555311060000     73.933103     18.088026     98.186038   
2   Row2  1555311000000     73.471742     25.843589     98.371549   
3   Row3  1555310940000     73.010381     27.772137     98.371549   
4   Row4  1555310880000     72.549020     18.402556     98.186038   

   AEAGHOAWE1A0  AEAGHOAWE1T1  AEAGHOAWE1T0  AEAGHOAWE3T0  AEAGHOAWE3A0  \
0     18.819155     93.337524     69.969526     95.445534      7.802471   
1     18.943335     92.869960     69.969526     95.445534     12.856953   
2     33.166077     92.343799     69.969526     95.628479     21.591973   
3     35.991205     91.876236     69.850105     95.607810     19.492370   
4     19.591687     91.408672     69.969526     95.607810      8.014898   

       ...       RWWIHOUT10V1  RWWIHOT7_RV0  RWWIHOT8_RV0  RWWIHOT9_RV0  \
0      ...                0.0     92.632593     44.620461     22.338103   
1      ...                0.0     82.082055     53.182296     26.967692   
2      ...                0.0     82.098144     53.029243     26.851837   
3      ...                0.0     82.074011     53.015226     26.266369   
4      ...                0.0     82.078296     53.172932     26.605640   

   RWWIHOT10RV0  RWWIHOTSURV0  RWWIHOTSUMV0  RWWIHO_VERV0  RWWIHO_UESV0  \
0     75.685755     73.945394      0.000000      0.000000      0.000000   
1     75.685755     66.649583     56.385432     68.734584      9.127668   
2     75.685755     66.587330     56.402658     68.853203      9.136596   
3     75.685755     66.373907     56.527297     69.391059      9.138625   
4     75.685755     66.529224     56.640964     69.299560      9.121256   

   RWWIHOSUMAV0  
0      0.000000  
1      2.275890  
2      2.275735  
3      2.281882  
4      2.269317  

[5 rows x 4220 columns]

In [4]:
test.columns

Index(['row ID', 'longTime', 'AEAGHOAWE2T1', 'AEAGHOAWE2A0', 'AEAGHOAWE2T0',
       'AEAGHOAWE1A0', 'AEAGHOAWE1T1', 'AEAGHOAWE1T0', 'AEAGHOAWE3T0',
       'AEAGHOAWE3A0',
       ...
       'RWWIHOUT10V1', 'RWWIHOT7_RV0', 'RWWIHOT8_RV0', 'RWWIHOT9_RV0',
       'RWWIHOT10RV0', 'RWWIHOTSURV0', 'RWWIHOTSUMV0', 'RWWIHO_VERV0',
       'RWWIHO_UESV0', 'RWWIHOSUMAV0'],
      dtype='object', length=4220)

In [5]:
import time
import datetime

longTime=test.loc[0:,['longTime']]
# print(type(longTime))
longTime=longTime.as_matrix()
# print('---',type(longTime))
a=[]
date_time_array=[]
for k in longTime:
#     print(type(k))
    a=np.append(a,k)

# print(a[0:])
# print(a[-2:])
str_time=[]
datetime_time=[]
count=0
for b in a:
#     print('type b: ',type(b))
    b=int(b) # make plain integer
    str_b=str(b)
    c=str_b[-3:]
    new_str_b=str_b.replace(c, '',1)
    new_str_b_time=int(new_str_b)
    
    now_time=datetime.datetime.fromtimestamp(new_str_b_time)
    convert_time=now_time.strftime('%Y-%m-%d %H:%M:%S')
    str_time.append(convert_time)
#     print(type(convert_time))
    
#     print('count_num: ',count,' unix_time: ',convert_time)
    date_time_obj = datetime.datetime.strptime(convert_time, '%Y-%m-%d %H:%M:%S')
    datetime_time.append(date_time_obj)
    date_time_array=np.append(date_time_array,date_time_obj)
#     print(date_time_obj)
#     print('count_num: ',count,' convert_time: ',convert_time," date_time_obj: ",date_time_obj," str_time",new_str_b_time)
#     count+=1

# print(date_time_array.size)
date_array=[]
for q in date_time_array[::1]:
# #     q=q.split(" ")
# #     split_q=np.append(split_q,q)
#     print("count: ",count," date: ",q.date()," time: ",q.time())
    count+=1
#     print(q)
#     q=str(q)
    date_array=np.append(date_array,q)
# print(date_time_array)
# print(date_array)
date_array[0].strftime('%A')# to get the day name
print(len(date_time_array))

C:\Users\atif\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


10000


In [6]:
print(str_time)

['2019-04-15 08:52:00', '2019-04-15 08:51:00', '2019-04-15 08:50:00', '2019-04-15 08:49:00', '2019-04-15 08:48:00', '2019-04-15 08:47:00', '2019-04-15 08:46:00', '2019-04-15 08:45:00', '2019-04-15 08:44:00', '2019-04-15 08:43:00', '2019-04-15 08:42:00', '2019-04-15 08:41:00', '2019-04-15 08:40:00', '2019-04-15 08:39:00', '2019-04-12 13:08:00', '2019-04-12 13:07:00', '2019-04-12 13:06:00', '2019-04-12 13:05:00', '2019-04-12 13:04:00', '2019-04-12 13:03:00', '2019-04-12 13:02:00', '2019-04-12 13:01:00', '2019-04-11 19:52:00', '2019-04-11 19:51:00', '2019-04-11 19:50:00', '2019-04-11 19:49:00', '2019-04-11 19:48:00', '2019-04-11 19:47:00', '2019-04-11 19:46:00', '2019-04-11 19:45:00', '2019-04-11 19:44:00', '2019-04-11 19:43:00', '2019-04-11 19:42:00', '2019-04-11 19:41:00', '2019-04-11 19:40:00', '2019-04-11 19:39:00', '2019-04-11 19:38:00', '2019-04-11 19:37:00', '2019-04-11 19:36:00', '2019-04-11 19:35:00', '2019-04-11 19:34:00', '2019-04-11 19:33:00', '2019-04-11 19:32:00', '2019-04-1

In [7]:
print(datetime_time)

[datetime.datetime(2019, 4, 15, 8, 52), datetime.datetime(2019, 4, 15, 8, 51), datetime.datetime(2019, 4, 15, 8, 50), datetime.datetime(2019, 4, 15, 8, 49), datetime.datetime(2019, 4, 15, 8, 48), datetime.datetime(2019, 4, 15, 8, 47), datetime.datetime(2019, 4, 15, 8, 46), datetime.datetime(2019, 4, 15, 8, 45), datetime.datetime(2019, 4, 15, 8, 44), datetime.datetime(2019, 4, 15, 8, 43), datetime.datetime(2019, 4, 15, 8, 42), datetime.datetime(2019, 4, 15, 8, 41), datetime.datetime(2019, 4, 15, 8, 40), datetime.datetime(2019, 4, 15, 8, 39), datetime.datetime(2019, 4, 12, 13, 8), datetime.datetime(2019, 4, 12, 13, 7), datetime.datetime(2019, 4, 12, 13, 6), datetime.datetime(2019, 4, 12, 13, 5), datetime.datetime(2019, 4, 12, 13, 4), datetime.datetime(2019, 4, 12, 13, 3), datetime.datetime(2019, 4, 12, 13, 2), datetime.datetime(2019, 4, 12, 13, 1), datetime.datetime(2019, 4, 11, 19, 52), datetime.datetime(2019, 4, 11, 19, 51), datetime.datetime(2019, 4, 11, 19, 50), datetime.datetime(201

In [8]:
test_new = test.assign(datetime=str_time)
test_new.head()

row ID       longTime  AEAGHOAWE2T1  AEAGHOAWE2A0  AEAGHOAWE2T0  \
0   Row0  1555311120000     74.451979     19.111606     98.371549   
1   Row1  1555311060000     73.933103     18.088026     98.186038   
2   Row2  1555311000000     73.471742     25.843589     98.371549   
3   Row3  1555310940000     73.010381     27.772137     98.371549   
4   Row4  1555310880000     72.549020     18.402556     98.186038   

   AEAGHOAWE1A0  AEAGHOAWE1T1  AEAGHOAWE1T0  AEAGHOAWE3T0  AEAGHOAWE3A0  \
0     18.819155     93.337524     69.969526     95.445534      7.802471   
1     18.943335     92.869960     69.969526     95.445534     12.856953   
2     33.166077     92.343799     69.969526     95.628479     21.591973   
3     35.991205     91.876236     69.850105     95.607810     19.492370   
4     19.591687     91.408672     69.969526     95.607810      8.014898   

          ...           RWWIHOT7_RV0  RWWIHOT8_RV0  RWWIHOT9_RV0  \
0         ...              92.632593     44.620461     22.338103   
1         ...              82.082055     53.182296     26.967692   
2         ...              82.098144     53.029243     26.851837   
3         ...              82.074011     53.015226     26.266369   
4         ...              82.078296     53.172932     26.605640   

   RWWIHOT10RV0  RWWIHOTSURV0  RWWIHOTSUMV0  RWWIHO_VERV0  RWWIHO_UESV0  \
0     75.685755     73.945394      0.000000      0.000000      0.000000   
1     75.685755     66.649583     56.385432     68.734584      9.127668   
2     75.685755     66.587330     56.402658     68.853203      9.136596   
3     75.685755     66.373907     56.527297     69.391059      9.138625   
4     75.685755     66.529224     56.640964     69.299560      9.121256   

   RWWIHOSUMAV0             datetime  
0      0.000000  2019-04-15 08:52:00  
1      2.275890  2019-04-15 08:51:00  
2      2.275735  2019-04-15 08:50:00  
3      2.281882  2019-04-15 08:49:00  
4      2.269317  2019-04-15 08:48:00  

[5 rows x 4221 columns]

In [9]:
te_1=test_new.loc[0:,['longTime','datetime']]
te_1.head()

longTime             datetime
0  1555311120000  2019-04-15 08:52:00
1  1555311060000  2019-04-15 08:51:00
2  1555311000000  2019-04-15 08:50:00
3  1555310940000  2019-04-15 08:49:00
4  1555310880000  2019-04-15 08:48:00

In [ ]:
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as md
import numpy as np
import datetime as dt
import time
%matplotlib inline

start_index=650
end_index=800
interval_index=1#place it after end_index. start_index:end_index:interval_index
minute_interval=10

longTime=test.loc[start_index:end_index:interval_index,['longTime']]
longTime=longTime.as_matrix()
print(longTime.size)
a=[]
date_time_array=[]
for k in longTime:
    a=np.append(a,k)

timestamp_array=[]
count=0
for b in a[::-1]:
    b=int(b) # make plain integer
    str_b=str(b)
    c=str_b[-3:]
    new_str_b=str_b.replace(c, '',1)
    new_str_b_time=int(new_str_b)
    timestamp_array=np.append(timestamp_array,new_str_b_time)
# print(timestamp_array[::5])
duration=1000
# timestamp_arrays=[]
# timestamp_arrays=np.linspace(timestamp_array[0],timestamp_array[0]+duration,len(timestamp_array))
# print(timestamp_arrays)
# print(np.linspace(timestamp_array[0],timestamp_array[0]+duration,len(timestamp_array)))

date_list=[dt.datetime.fromtimestamp(ts) for ts in timestamp_array]
# for r in date_list:
#     print(r)
# print(date_list[::5])

datenums_array=md.date2num(date_list)
datenums_array=datenums_array[0:60]
# for w in datenums_array:
#     print(w)
# print(type(datenums_array))

value_1=test.loc[start_index:end_index:interval_index,['RWWIHOA_MWT0','AEDAT_3_80V0']]
value_1=value_1.as_matrix()

RWWIHOA_MWT0=value_1[::,0]
RWWIHOA_MWT0=RWWIHOA_MWT0[::-1]

AEDAT_3_80V0=value_1[::,1]
AEDAT_3_80V0=AEDAT_3_80V0[::-1]

print(max(RWWIHOA_MWT0),'\n',min(RWWIHOA_MWT0))
print(max(AEDAT_3_80V0),'\n',min(AEDAT_3_80V0))

plt.title('graph')
plt.subplots_adjust(bottom=.2)
plt.xticks( rotation=25)
ax=plt.gca()

minlocator = md.MinuteLocator(interval=minute_interval) # to plot every minute of an range
# minlocator.MAXTICKS  = 40000
ax.xaxis.set_major_locator(minlocator)

xfmt = md.DateFormatter('%Y-%m-%d %H:%M:%S')
ax.xaxis.set_major_formatter(xfmt)
# plt.subplot(2,1,1)
plt.plot(datenums_array,RWWIHOA_MWT0[0:60],color='orange') #you can give here datenums_array
plt.plot(datenums_array,AEDAT_3_80V0[0:60],color='RED')
# plt.plot(datenums_array,value_1,color='red')
plt.gcf().autofmt_xdate() # to beautify the X label
# plt.title('2nd graph')
# plt.subplot(1,2,2) #1 row, 2 cols, position
# plt.xlabel('date_time')
# plt.ylabel('value_1_rev')
# plt.plot(datenums_array,value_1)
# plt.xlim((min(datenums_array),max(datenums_array)))
plt.xlim(datenums_array[0],datenums_array[-1])
# plt.ylim(40,60)
# print(min(datenums_array),max(datenums_array))
# print(datenums_array[0],datenums_array[-1])
plt.show()

In [ ]:
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as md
import numpy as np
import datetime as dt
import time
%matplotlib inline
start_index=8000
end_index=start_index+1000
interval_index=1#place it after end_index. start_index:end_index:interval_index
minute_interval=5

# The following function is to plot graph time vs any parameter

In [ ]:
def time_graph(y_item,y_label):
    global start_index
    global end_index
    global interval_index
    global minute_interval
    
    longTime=test.loc[start_index:end_index:interval_index,['longTime']]
    longTime=longTime.as_matrix()
    print(longTime.size)
    a=[]
    date_time_array=[]
    for k in longTime:
        a=np.append(a,k)

    timestamp_array=[]
    count=0
    for b in a[::-1]:
        b=int(b) # make plain integer
        str_b=str(b)
        c=str_b[-3:]
        new_str_b=str_b.replace(c, '',1)
        new_str_b_time=int(new_str_b)
        timestamp_array=np.append(timestamp_array,new_str_b_time)
# print(timestamp_array[::5])
#     duration=1000
# timestamp_arrays=[]
# timestamp_arrays=np.linspace(timestamp_array[0],timestamp_array[0]+duration,len(timestamp_array))
# print(timestamp_arrays)
# print(np.linspace(timestamp_array[0],timestamp_array[0]+duration,len(timestamp_array)))

    date_list=[dt.datetime.fromtimestamp(ts) for ts in timestamp_array]
# for r in date_list:
#     print(r)
# print(date_list[::5])

    datenums_array=md.date2num(date_list)
    
    value_1=test.loc[start_index:end_index:interval_index,[y_item]]
    value_1=value_1.as_matrix()
    value_y=value_1[::,0]
    value_y=value_y[::-1]
    print('max: ',max(value_y),'\t min: ',min(value_y))
    
    plt.title('graph')
    plt.subplots_adjust(bottom=.2)
    plt.xticks( rotation=25)
    ax=plt.gca()
    
    minlocator = md.MinuteLocator(interval=minute_interval) # to plot every minute of an range
#     minlocator.MAXTICKS  = 40000
    ax.xaxis.set_major_locator(minlocator)
    
    xfmt = md.DateFormatter('%Y-%m-%d %H:%M:%S')
    ax.xaxis.set_major_formatter(xfmt)
    plt.plot(datenums_array,value_y,color='orange') #you can give here datenums_array
    plt.title('time_series_variation_in_power_plant')
    plt.ylabel(y_label)
    plt.xlabel('Time')
    plt.gcf().autofmt_xdate() # to beautify the X label
# plt.xlim((min(datenums_array),max(datenums_array)))
    plt.xlim(datenums_array[0],datenums_array[-1])
#     plt.ylim(value_y[0],value_y[-1])
# plt.subplots_adjust(hspace=1.4, wspace=1.4)
    plt.tight_layout() #to remove overlapping among of subplot
    plt.show()

# time_graph(y_item='AEDATZ_HO_V0',y_label='fig_1_sig_14') #fig 1 signal 14
# time_graph(y_item='RWWIHOA_HWT0',y_label='fig_2_Hot_wind_Temp_to_Mixer') #fig 2 signal 17
# time_graph(y_item='AEWIHOAKZ_V0',y_label='fig_2_Cold_wind_Temp_to_Mixer') #fig 2 signal 18
# time_graph(y_item='RWWIHOA_MWT0',y_label='Temparature_to_Blast_Furnace') #fig 2 signal 19


# time_graph(y_item='AEDAHO_T8_V2',y_label='T8_input') #fig 1 signal 16 input
# time_graph(y_item='AEDAHO_T9_V2',y_label='T9_input') #fig 1 signal 17 input
time_graph(y_item='AEDAHO_T9_V2',y_label='T9_input')

# Below code for Linear regression method Training and testing

In [16]:
from sklearn import metrics
from sklearn.linear_model import LinearRegression

# from sklearn.model_selection import train_test_split

# to concatenate different array

In [10]:
train_data=test.loc[200:210,['AEDATZ_HO_V0','RWWIHOA_HWT0','AEWIHOAKZ_V0','RWWIHOA_MWT0','AEDAHO_T9_V2']]
train_data_array=train_data.as_matrix()
print(train_data_array)
# d=np.column_stack((date_time_array,train_data_array))
# print(d[0:][0:][0:])

[[33.32389614 89.51739725  0.         93.09289835 42.04031682]
 [35.0122334  89.58221378  0.         93.18238764 42.10515309]
 [36.9366052  89.56357891  0.         93.18564505 42.09770852]
 [37.42514829 89.50038452  0.         93.11649468 42.12710965]
 [36.84384805 89.55953344  0.         93.11405163 42.00102715]
 [35.94133904 89.50038452  0.         93.09696017 42.05430966]
 [35.02425622 89.22731038  0.         92.87242756 42.05777726]
 [33.77097734 88.93237686  0.         92.64544195 41.76453002]
 [33.38591274 87.98029688  0.         91.72205664 41.92656193]
 [34.09272162 88.42676241  0.         91.86280043 42.04224163]
 [35.26408446 88.52642537  0.         91.90266393 42.02645132]]


C:\Users\atif\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [14]:
# train_data=test.loc[200:8000,['AEDATZ_HO_V0','RWWIHOA_HWT0','AEWIHOAKZ_V0','RWWIHOA_MWT0','AEDAHO_T9_V2']]
# train_data_array=train_data.as_matrix()
train_input=train_data_array[:,:4]
train_output=train_data_array[:,4]
# print(train_input)

In [17]:
train_model=LinearRegression(fit_intercept=False).fit(train_input,train_output)
print(train_model)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)


In [18]:
test_data=test.loc[8000:9000,['longTime','AEDATZ_HO_V0','RWWIHOA_HWT0','AEWIHOAKZ_V0','RWWIHOA_MWT0','AEDAHO_T9_V2']]
test_data_array=test_data.as_matrix()
test_input=test_data_array[:,:5]
predicted_op=train_model.predict(test_input)
print(predicted_op)

actual_op=test_data_array[:,5]
print(actual_op)

C:\Users\atif\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


ValueError: shapes (1001,5) and (4,) not aligned: 5 (dim 1) != 4 (dim 0)

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import math
print('Slope:' ,train_model.coef_)
print('Intercept:', train_model.intercept_)
print('r_2 statistic: %.2f' % r2_score(actual_op,predicted_op))
print("Mean_absolute_error: %.2f" % mean_absolute_error(actual_op,predicted_op))
print("Mean squared error: %.2f" % mean_squared_error(actual_op,predicted_op))
RMSE=math.sqrt(mean_squared_error(actual_op,predicted_op))
print('RMSE: ',RMSE)

In [ ]:
predicted_op_rev=predicted_op[0:60]
predicted_op_rev=predicted_op_rev[::-1]
# # print(predicted_op_rev)
actual_op_rev=actual_op[0:60]
actual_op_rev=actual_op_rev[::-1]

import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as md
import numpy as np
import datetime as dt
import time
%matplotlib inline

start_index=8000
end_index=start_index+59
interval_index=1#place it after end_index. start_index:end_index:interval_index
minute_interval=5

longTime=test.loc[start_index:end_index:interval_index,['longTime']]
longTime=longTime.as_matrix()
print(longTime.size)
a=[]
date_time_array=[]
for k in longTime:
    a=np.append(a,k)

timestamp_array=[]
count=0
for b in a:
    b=int(b) # make plain integer
    str_b=str(b)
    c=str_b[-3:]
    new_str_b=str_b.replace(c, '',1)
    new_str_b_time=int(new_str_b)
    timestamp_array=np.append(timestamp_array,new_str_b_time)

date_list=[dt.datetime.fromtimestamp(ts) for ts in timestamp_array]

datenums_array=md.date2num(date_list)

plt.title('graph')
plt.subplots_adjust(bottom=.2)
plt.xticks( rotation=25)
ax=plt.gca()

minlocator = md.MinuteLocator(interval=minute_interval) # to plot every minute of an range
# minlocator.MAXTICKS  = 40000
ax.xaxis.set_major_locator(minlocator)

xfmt = md.DateFormatter('%Y-%m-%d %H:%M:%S')
ax.xaxis.set_major_formatter(xfmt)
plt.plot(datenums_array,predicted_op[490:490+60],color='green') #you can give here datenums_array
plt.plot(datenums_array,actual_op[490:490+60],color='RED')
plt.gcf().autofmt_xdate() # to beautify the X label

plt.xlim(datenums_array[0],datenums_array[-1])
plt.show()

In [ ]:
print(predicted_op[499])
print(actual_op[500])

In [ ]:
test_data_rev=test.loc[8000:9000,['AEDATZ_HO_V0','RWWIHOA_HWT0','AEWIHOAKZ_V0','RWWIHOA_MWT0','AEDAHO_T9_V2']]
test_data_array_rev=test_data_rev.as_matrix()
test_input_rev=test_data_array_rev[:,:4]
test_input_rev=test_input_rev[::-1]
predicted_op_rev=train_model.predict(test_input_rev)
print('rev: ',predicted_op_rev)
print('\n normal: ',predicted_op)
actual_op=test_data_array[:,4]
actual_op_rev=actual_op[::-1]
print(actual_op_rev)

In [ ]:
test_rev=test_data_array_1[::-1]
print(test_rev)

In [ ]:
a=test.loc[8000:8009,['longTime']]
print(type(a))
a=a.as_matrix()
a=a[::]

plt.plot(a,predicted_op[0:10],color='green')
plt.plot(a,actual_op[0:10],color='red')
plt.show()

In [ ]:
from statsmodels.tsa.arima_model import ARMA
from random import random
# contrived dataset
data = [x + random() for x in range(1, 100)]
# fit model
model = ARMA(data, order=(0, 1))
model_fit = model.fit(disp=False)
# make prediction
yhat = model_fit.predict(len(data), len(data))
print(yhat)

In [ ]:
from statsmodels.tsa.arima_model import ARMA
from random import random
# contrived dataset
data = [random() for x in range(1, 100)]
# fit model
model = ARMA(data, order=(2, 1))
model_fit = model.fit(disp=False)
# make prediction
yhat = model_fit.predict(len(data), len(data))
print(yhat)